// GENERATED by scripts/generate-kernel-modules.ts — do not edit by hand.
// Run `pnpm generate:modules` after adding or removing a domain/feature module.ts.
// Side-effect imports so every module self-registers on load.
import "../domains/aisle/module.js";
import "../domains/grocery/module.js";
import "../domains/meal-planner/module.js";
import "../domains/meal-type/module.js";
import "../domains/meal/module.js";
import "../domains/menu/module.js";
import "../domains/pantry/module.js";
import "../domains/recipe/module.js";
import "../features/discover/module.js";
import "../features/photo-gen/module.js";
