// GENERATED by scripts/generate-kernel-modules.ts — do not edit by hand.
// Run `pnpm generate:modules` after adding or removing a domain module.ts.
// Side-effect imports so every domain module self-registers on load.
import "../aisle/module.js";
import "../meal/module.js";
import "../meal-type/module.js";
import "../menu/module.js";
import "../pantry/module.js";
import "../recipe/module.js";
