/**
 * In-memory cache of AI-generated photo previews awaiting attachment.
 *
 * `generate_photo` (preview mode) stashes the freshly generated bytes here under
 * an opaque `gen_…` token and returns that token; `upload_photo` later resolves
 * the token to those exact bytes via its `generation_token` source. This is what
 * lets a user attach the image they previewed without re-generating it (image
 * models are non-deterministic) or round-tripping multi-MB base64 through the
 * model — the bytes stay server-side and only a tiny token travels.
 *
 * Bounded (ring buffer, `MAX_GENERATED_IMAGES`) and short-TTL
 * (`GENERATED_IMAGE_TTL_SECONDS`): previews are inherently throwaway, so when
 * full the OLDEST is evicted — harmless here (unlike the auth TTL stores, a
 * dropped preview just means "generate again"), which is why this evicts rather
 * than rejecting. In-memory only; lost on restart.
 */

import { randomBytes } from "node:crypto";

/** A stashed generated image plus the metadata the attach path needs. */
export interface GeneratedImageEntry {
  readonly bytes: Buffer;
  readonly mimeType: string;
  /** The recipe the preview was generated for (the prompt was built from it). */
  readonly recipeUid: string;
  /** The image model that produced it (for the attach confirmation message). */
  readonly model: string;
  /** Unix seconds; drives TTL expiry. */
  readonly createdAt: number;
}

/** Preview lifetime before its token stops resolving (1 hour). */
export const GENERATED_IMAGE_TTL_SECONDS = 60 * 60;

/** Most previews held at once; the oldest is evicted past this. */
export const MAX_GENERATED_IMAGES = 8;

export class GeneratedImageStore {
  // Map preserves insertion order, so the first key is the oldest entry.
  private readonly _entries: Map<string, GeneratedImageEntry> = new Map();
  private readonly _ttlMs: number;
  private readonly _maxEntries: number;
  private readonly _now: () => number;

  constructor(opts?: { readonly ttlMs?: number; readonly maxEntries?: number; readonly now?: () => number }) {
    this._ttlMs = opts?.ttlMs ?? GENERATED_IMAGE_TTL_SECONDS * 1000;
    this._maxEntries = opts?.maxEntries ?? MAX_GENERATED_IMAGES;
    this._now = opts?.now ?? Date.now;
  }

  /**
   * Stash a generated image and return its opaque single-use token. Evicts the
   * oldest entry first if the store is at capacity.
   */
  put(entry: Omit<GeneratedImageEntry, "createdAt">): string {
    if (this._entries.size >= this._maxEntries) {
      const oldest = this._entries.keys().next().value;
      if (oldest !== undefined) this._entries.delete(oldest);
    }
    const token = `gen_${randomBytes(16).toString("base64url")}`;
    this._entries.set(token, { ...entry, createdAt: Math.floor(this._now() / 1000) });
    return token;
  }

  /**
   * Read an entry WITHOUT removing it; null if unknown or expired (an expired
   * entry is lazily evicted). Use this to validate/use a token while leaving it
   * spendable, then `consume` it only once the work that needed it has
   * succeeded — so a failed or mistargeted attach doesn't burn the preview.
   */
  peek(token: string): GeneratedImageEntry | null {
    const entry = this._entries.get(token);
    if (entry === undefined) return null;
    if (entry.createdAt + this._ttlMs / 1000 < Math.floor(this._now() / 1000)) {
      this._entries.delete(token);
      return null;
    }
    return entry;
  }

  /** Retrieve and remove an entry; null if the token is unknown or expired. */
  consume(token: string): GeneratedImageEntry | null {
    const entry = this._entries.get(token);
    if (entry === undefined) return null;
    this._entries.delete(token);
    const expiresAt = entry.createdAt + this._ttlMs / 1000;
    if (expiresAt < Math.floor(this._now() / 1000)) return null;
    return entry;
  }

  get size(): number {
    return this._entries.size;
  }
}
