apiVersion: v1
kind: Service
metadata:
  name: mcp-paprika
  namespace: mcp-paprika
  labels:
    app.kubernetes.io/name: mcp-paprika
    app.kubernetes.io/instance: mcp-paprika
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mcp-paprika
    app.kubernetes.io/instance: mcp-paprika
  ports:
    - name: http
      port: 80
      targetPort: http
