#!/usr/bin/env bash
# Regenerates src/paprika/__fixtures__/recipe-hashes.ts by driving the shipped
# Paprika.framework's real Recipe.hashValues getter over synthetic recipes.
#
# Prerequisites (macOS only):
#   - Paprika Recipe Manager 3 installed (default /Applications, or set
#     PAPRIKA_FRAMEWORK=/path/to/Paprika.framework)
#   - Xcode command-line tools (swiftc, clang)
#
# Usage:  bash scripts/recipe-hash-fixtures/run.sh
# Then:   pnpm vitest run src/paprika/recipe-hash.test.ts
#
# A diff in the committed fixture module after running this = Paprika changed its
# hash algorithm; computeRecipeHash (src/paprika/recipe-hash.ts) must be re-derived.
set -euo pipefail
cd "$(dirname "$0")"
repo_root="$(cd ../.. && pwd)"
out="$repo_root/src/paprika/__fixtures__/recipe-hashes.ts"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

clang -c shim.c -o "$tmp/shim.o"
swiftc generate.swift "$tmp/shim.o" -import-objc-header shim.h \
  -framework CoreData -framework Foundation -o "$tmp/generate"
"$tmp/generate" > "$tmp/fixtures.json"

{
  cat <<'HEADER'
// Ground-truth recipe-hash fixtures. Generated by driving the shipped
// Paprika.framework's real `Recipe.hashValues` getter over synthetic recipes
// (in-memory Core Data) and capturing the authoritative SHA-256 (#167). These pin
// `computeRecipeHash`'s NSJSONSerialization / slash-escape / category-sort /
// empty-vs-null replication to real framework output. Do not hand-edit hashes —
// regenerate with `bash scripts/recipe-hash-fixtures/run.sh`. All cases are live
// recipes (in_trash/deleted false), the only hashes Paprika stores; trash
// independence is covered by a unit test, not a fixture.

export interface RecipeHashFixture {
  readonly name: string;
  readonly recipe: Record<string, unknown>;
  readonly expectedHash: string;
}

export const RECIPE_HASH_FIXTURES: ReadonlyArray<RecipeHashFixture> =
HEADER
  jq 'map({name, recipe, expectedHash})' "$tmp/fixtures.json"
  echo ";"
} > "$out"

echo "wrote $(jq length "$tmp/fixtures.json") fixtures -> $out"
