// Generates src/kernel/modules.generated.ts — a barrel of side-effect imports so
// every domain module self-registers on load (the discovery half of the kernel).
// A dumb filesystem glob: NO TypeScript compiler API, no bundler. A domain is any
// top-level src/<domain>/ directory that contains a `module.ts`. Run via
// `pnpm generate:modules`; the output is committed.
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

// Anchor to the repo root (like generate-har-fixtures.ts / generate-tool-reference.ts)
// so the generator is cwd-independent — running it from anywhere is safe.
const PROJECT_ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const SRC = join(PROJECT_ROOT, "src");
const OUT_DIR = join(SRC, "kernel");
const OUT = join(OUT_DIR, "modules.generated.ts");

async function main(): Promise<void> {
  const entries = await readdir(SRC, { withFileTypes: true });
  const domains: Array<string> = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    // A domain is any top-level src/<domain>/ directory holding a `module.ts`.
    const contents = await readdir(join(SRC, entry.name));
    if (contents.includes("module.ts")) domains.push(entry.name);
  }
  domains.sort();

  const lines = [
    "// GENERATED by scripts/generate-kernel-modules.ts — do not edit by hand.",
    "// Run `pnpm generate:modules` after adding or removing a domain module.ts.",
    "// Side-effect imports so every domain module self-registers on load.",
    ...domains.map((d) => `import "../${d}/module.js";`),
  ];
  // Keep the barrel a module even with zero domains (none exist until the first
  // domain migrates), so it type-checks cleanly under isolatedModules.
  if (domains.length === 0) lines.push("export {};");
  lines.push("");

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT, lines.join("\n"));
  process.stderr.write(`generated ${OUT} (${domains.length.toString()} modules)\n`);
}

await main();
