/**
 * Generates docs/tools/README.md (a single, source-of-truth reference for
 * every MCP tool the server registers) by building the server with a stub
 * context and introspecting the live tool registry. The Zod input schemas in
 * src/tools/ and the registration in src/server/build.ts remain canonical; this
 * file derives from them so it can never drift.
 *
 * Run: npx tsx scripts/generate-tool-reference.ts  (or: pnpm generate:tool-reference)
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import type { AppContext } from "../src/server/app-context.js";

import { buildMcpServer } from "../src/server/build.js";
import { SILENT_LOG } from "../src/utils/log.js";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const OUT = join(__dirname, "..", "docs", "tools", "README.md");

// `buildMcpServer` only reads `ctx.log` at registration time (each register*
// calls `ctx.log.child(...)` before `server.registerTool(...)`); the tool
// handlers (which use the rest of the context) are closures that are never
// invoked here. The two opt-in tools gate on `vectorStore` / `photographyClient`
// being non-null, so non-null them to register the full surface.
const stub = {
  log: SILENT_LOG,
  vectorStore: {},
  photographyClient: {},
} as unknown as AppContext;

interface ZodLike {
  readonly description?: string;
  readonly shape?: Record<string, ZodLike>;
  isOptional?: () => boolean;
}

interface RegisteredTool {
  readonly description?: string;
  readonly inputSchema?: ZodLike;
  readonly enabled: boolean;
}

function paramRows(inputSchema: ZodLike | undefined): string[] {
  const shape = inputSchema?.shape ?? (inputSchema as Record<string, ZodLike> | undefined);
  if (!shape) return [];
  const rows: string[] = [];
  for (const [name, field] of Object.entries(shape)) {
    // A raw shape's values are Zod types; a ZodObject's `.shape` also is. Skip
    // anything that doesn't look like a Zod field.
    if (typeof field !== "object" || field === null) continue;
    const optional = typeof field.isOptional === "function" ? field.isOptional() : false;
    const desc = field.description ?? "";
    rows.push(`- \`${name}\`${optional ? " _(optional)_" : ""}${desc ? ` — ${desc}` : ""}`);
  }
  return rows;
}

function main(): void {
  const server = buildMcpServer(stub);
  const registry = (server as unknown as { _registeredTools: Record<string, RegisteredTool> })._registeredTools;

  const names = Object.keys(registry).sort((a, b) => a.localeCompare(b));

  const lines: string[] = [
    "<!-- Generated by scripts/generate-tool-reference.ts. Do not edit by hand.",
    "     Regenerate after changing a tool: pnpm generate:tool-reference -->",
    "",
    "# Paprika MCP tools",
    "",
    "A generated reference for every tool the server registers. The authoritative contracts are the",
    "Zod `inputSchema` in each `src/tools/*.ts` and the registration list in `src/server/build.ts`;",
    "this page is derived from them. Two tools are opt-in and only appear to a client when configured:",
    "`discover_recipes` (semantic search) and `generate_recipe_photo` (AI photos).",
    "",
  ];

  for (const name of names) {
    const tool = registry[name];
    if (tool === undefined) continue;
    lines.push(`## \`${name}\``, "");
    if (tool.description) lines.push(tool.description, "");
    const params = paramRows(tool.inputSchema);
    if (params.length > 0) {
      lines.push("**Parameters**", "", ...params, "");
    } else {
      lines.push("_No parameters._", "");
    }
  }

  writeFileSync(OUT, lines.join("\n").replace(/\n+$/, "\n"), "utf-8");
  process.stdout.write(`Wrote ${OUT} (${names.length} tools)\n`);
}

main();
