/**
 * Generates docs/tools/README.md (a single, source-of-truth reference for
 * every MCP tool the server registers) by building the composition kernel with a
 * stub Infra and introspecting the live tool registry. The Zod input schemas in
 * each domain's `tools/` and the module registrations under `src/domains/` remain
 * canonical; this file derives from them so it can never drift.
 *
 * Run: npx tsx scripts/generate-tool-reference.ts  (or: pnpm generate:tool-reference)
 */

import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import type { Infra } from "../src/kernel/registry.js";
import type { PaprikaClient } from "../src/paprika/client.js";
import type { PaprikaConfig } from "../src/utils/config.js";

import { GeneratedImageStore } from "../src/features/generated-image-store.js";
import { buildKernel } from "../src/kernel/registry.js";
import { buildBrandedServer } from "../src/server/build.js";
import { createIndexEvents } from "../src/server/index-events.js";
import { SILENT_LOG } from "../src/utils/log.js";
// Side-effect: every domain/feature module self-registers, so buildKernel's default
// module list is populated.
import "../src/kernel/modules.generated.js";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const OUT = join(__dirname, "..", "docs", "tools", "README.md");

// A minimal Infra. Module `.self` factories don't call the client (they hydrate from
// the cache dir and bind closures), so an auto-stub client suffices; the initial
// `syncOnce` that buildKernel runs DOES call it, but syncOnce never throws — its
// reconciles fail and are swallowed, which is harmless here since we only introspect
// the registered tools afterward. The two feature tools (discover_recipes,
// generate_recipe_photo) register UNCONDITIONALLY (they no-op when their client is
// null — ADR-0009 §5), so a features-off config still yields the full surface.
const stubClient = new Proxy({}, { get: () => () => undefined }) as unknown as PaprikaClient;
const config = {
  transport: "stdio",
  sync: { enabled: false, pendingWriteTtl: 0, interval: 0, recipeFetchConcurrency: 1 },
} as unknown as PaprikaConfig;

interface ZodLike {
  readonly description?: string;
  readonly shape?: Record<string, ZodLike>;
  isOptional?: () => boolean;
}

interface RegisteredTool {
  readonly description?: string;
  readonly inputSchema?: ZodLike;
  readonly enabled: boolean;
}

function paramRows(inputSchema: ZodLike | undefined): string[] {
  const shape = inputSchema?.shape ?? (inputSchema as Record<string, ZodLike> | undefined);
  if (!shape) return [];
  const rows: string[] = [];
  for (const [name, field] of Object.entries(shape)) {
    // A raw shape's values are Zod types; a ZodObject's `.shape` also is. Skip
    // anything that doesn't look like a Zod field.
    if (typeof field !== "object" || field === null) continue;
    const optional = typeof field.isOptional === "function" ? field.isOptional() : false;
    const desc = field.description ?? "";
    rows.push(`- \`${name}\`${optional ? " _(optional)_" : ""}${desc ? ` — ${desc}` : ""}`);
  }
  return rows;
}

async function main(): Promise<void> {
  const infra: Infra = {
    client: stubClient,
    cacheDir: mkdtempSync(join(tmpdir(), "paprika-tool-reference-")),
    notifier: { resourceListChanged: () => {}, loggingMessage: async () => {} },
    log: SILENT_LOG,
    config,
    indexEvents: createIndexEvents(SILENT_LOG),
    generatedImageStore: new GeneratedImageStore(),
  };

  const kernel = await buildKernel(infra);
  const server = buildBrandedServer();
  kernel.registerAll(server);
  const registry = (server as unknown as { _registeredTools: Record<string, RegisteredTool> })._registeredTools;

  const names = Object.keys(registry).sort((a, b) => a.localeCompare(b));

  const lines: string[] = [
    "<!-- Generated by scripts/generate-tool-reference.ts. Do not edit by hand.",
    "     Regenerate after changing a tool: pnpm generate:tool-reference -->",
    "",
    "# Paprika MCP tools",
    "",
    "A generated reference for every tool the server registers. The authoritative contracts are the",
    "Zod `inputSchema` in each domain's `tools/*.ts` and the module registrations under `src/domains/`;",
    "this page is derived from them. Two tools are opt-in and only behave when configured:",
    "`discover_recipes` (semantic search) and `generate_recipe_photo` (AI photos).",
    "",
  ];

  for (const name of names) {
    const tool = registry[name];
    if (tool === undefined) continue;
    lines.push(`## \`${name}\``, "");
    if (tool.description) lines.push(tool.description, "");
    const params = paramRows(tool.inputSchema);
    if (params.length > 0) {
      lines.push("**Parameters**", "", ...params, "");
    } else {
      lines.push("_No parameters._", "");
    }
  }

  writeFileSync(OUT, lines.join("\n").replace(/\n+$/, "\n"), "utf-8");
  process.stdout.write(`Wrote ${OUT} (${names.length} tools)\n`);
}

await main();
