// Generates src/kernel/modules.generated.ts — a barrel of side-effect imports so
// every domain/feature module self-registers on load (the discovery half of the
// kernel). A dumb filesystem glob: NO TypeScript compiler API, no bundler. A module
// is any `module.ts` under src/ at any depth — data domains live at
// src/<domain>/module.ts, features at src/features/<feature>/module.ts. Run via
// `pnpm generate:modules`; the output is committed.
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { join, sep } from "node:path";
import { fileURLToPath } from "node:url";

// Anchor to the repo root (like generate-har-fixtures.ts / generate-tool-reference.ts)
// so the generator is cwd-independent — running it from anywhere is safe.
const PROJECT_ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const SRC = join(PROJECT_ROOT, "src");
const OUT_DIR = join(SRC, "kernel");
const OUT = join(OUT_DIR, "modules.generated.ts");

async function main(): Promise<void> {
  // Recursively find every `module.ts` under src/. Paths come back relative to SRC
  // (e.g. "recipe/module.ts", "features/discover/module.ts"); normalize the OS
  // separator to "/" for the emitted import specifiers.
  const entries = await readdir(SRC, { recursive: true });
  const modulePaths = entries
    .map((p) => p.split(sep).join("/"))
    .filter((p) => p === "module.ts" || p.endsWith("/module.ts"))
    .sort();

  const lines = [
    "// GENERATED by scripts/generate-kernel-modules.ts — do not edit by hand.",
    "// Run `pnpm generate:modules` after adding or removing a domain/feature module.ts.",
    "// Side-effect imports so every module self-registers on load.",
    ...modulePaths.map((p) => `import "../${p.replace(/\.ts$/, ".js")}";`),
  ];
  // Keep the barrel a module even with zero modules (none exist until the first
  // domain migrates), so it type-checks cleanly under isolatedModules.
  if (modulePaths.length === 0) lines.push("export {};");
  lines.push("");

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT, lines.join("\n"));
  process.stderr.write(`generated ${OUT} (${modulePaths.length.toString()} modules)\n`);
}

await main();
