// Shared discovery + rendering for the tool reference (docs/tools/README.md).
// Both scripts/generate-tool-reference.ts (writes the file) and the tool-reference
// tests (assert no drift / freshness) import from here, so the generator and its
// guards read the surface the SAME way. NO kernel boot, NO McpServer, NO SDK
// internals: each tool is `defineTool(spec, …)` data, so importing a tool module
// and reading `.spec` is the whole job.

import { readdir } from "node:fs/promises";
import { join, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import type { ToolSpec } from "../src/kernel/tool.js";

// Anchor to the repo root (like the sibling generators) so discovery is
// cwd-independent — running from anywhere, or from a test, finds the same files.
const REPO_ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const SRC = join(REPO_ROOT, "src");

/** A ToolDef as seen structurally — enough to pull its spec, without importing the type machinery. */
interface ToolDefLike {
  readonly spec: ToolSpec;
  readonly register: unknown;
}

function isToolDef(v: unknown): v is ToolDefLike {
  if (typeof v !== "object" || v === null) return false;
  const o = v as { spec?: { name?: unknown }; register?: unknown };
  return typeof o.register === "function" && typeof o.spec?.name === "string";
}

/** Every tool module — a `*.ts` file under any `tools/` directory in `src` — excluding colocated `*.test.ts`. */
async function toolModulePaths(): Promise<ReadonlyArray<string>> {
  const entries = await readdir(SRC, { recursive: true });
  return entries
    .map((p) => p.split(sep).join("/"))
    .filter((p) => /(?:^|\/)tools\/[^/]+\.ts$/.test(p) && !p.includes(".test."))
    .sort()
    .map((p) => join(SRC, p));
}

/**
 * Discover every registered tool's spec by importing the tool modules and reading
 * their exported `defineTool` results (individually exported, or inside a bundle
 * array like `pantryStockTools`). Deduped by name and sorted, so the output is
 * deterministic. This is the SAME set the kernel registers, because a module's
 * `tools: [...]` lists these exact `ToolDef`s — the drift test pins that equality.
 */
export async function collectToolSpecs(): Promise<ReadonlyArray<ToolSpec>> {
  const byName = new Map<string, ToolSpec>();
  for (const file of await toolModulePaths()) {
    const mod = (await import(pathToFileURL(file).href)) as Record<string, unknown>;
    for (const value of Object.values(mod)) {
      const candidates = Array.isArray(value) ? (value as ReadonlyArray<unknown>) : [value];
      for (const candidate of candidates) {
        if (isToolDef(candidate)) byName.set(candidate.spec.name, candidate.spec);
      }
    }
  }
  return [...byName.values()].sort((a, b) => a.name.localeCompare(b.name));
}

interface ZodLike {
  readonly description?: string;
  readonly shape?: Record<string, ZodLike>;
  isOptional?: () => boolean;
}

/** One bullet per input field. Handles both spec forms: a raw shape, or a whole Zod object (read `.shape`). */
function paramRows(inputSchema: ToolSpec["inputSchema"]): ReadonlyArray<string> {
  const schema = inputSchema as ZodLike;
  const shape = schema.shape ?? (inputSchema as Record<string, ZodLike>);
  const rows: Array<string> = [];
  for (const [name, field] of Object.entries(shape)) {
    // A raw shape's values are Zod types; a ZodObject's `.shape` also is. Skip anything else.
    if (typeof field !== "object" || field === null) continue;
    const optional = typeof field.isOptional === "function" ? field.isOptional() : false;
    const desc = field.description ?? "";
    rows.push(`- \`${name}\`${optional ? " _(optional)_" : ""}${desc ? ` — ${desc}` : ""}`);
  }
  return rows;
}

/** The behavior hints from a tool's annotations, as a short readable list. */
function hintLabels(annotations: ToolSpec["annotations"]): ReadonlyArray<string> {
  const labels: Array<string> = [annotations.readOnlyHint === true ? "read-only" : "write"];
  if (annotations.destructiveHint === true) labels.push("destructive");
  if (annotations.idempotentHint === true) labels.push("idempotent");
  if (annotations.openWorldHint === true) labels.push("open-world");
  return labels;
}

/**
 * Render the full `docs/tools/README.md` from a sorted spec list. Pure (no I/O), so
 * the freshness test can assert the committed file equals this exactly.
 */
export function renderToolReference(specs: ReadonlyArray<ToolSpec>): string {
  const lines: Array<string> = [
    "<!-- Generated by scripts/generate-tool-reference.ts. Do not edit by hand.",
    "     Regenerate after changing a tool: pnpm generate:tool-reference -->",
    "",
    "# Paprika MCP tools",
    "",
    "A generated reference for every tool the server registers, derived from the `defineTool` specs in",
    "each domain's `tools/*.ts` (no runtime boot — the spec IS the source). Two tools are opt-in and only",
    "behave when configured: `discover_recipes` (semantic search) and `generate_recipe_photo` (AI photos).",
    "",
  ];

  for (const spec of specs) {
    lines.push(`## \`${spec.name}\``, "");
    lines.push(`**${spec.title}** — ${hintLabels(spec.annotations).join(", ")}`, "");
    if (spec.description) lines.push(spec.description, "");
    const params = paramRows(spec.inputSchema);
    if (params.length > 0) {
      lines.push("**Parameters**", "", ...params, "");
    } else {
      lines.push("_No parameters._", "");
    }
  }

  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}
